### ISSUE TITLE
بازه تاریخی

### ISSUE THREAD

**Issue by javad-heidarpour** [mohammadoftadeh/vue3-persian-datepicker#1]
سلام
ضمن تشکر از ارائه این کامپوننت، نحوه ایجاد محدودیت و ایجاد یک بازه تاریخی چگونه باید اقدام کنیم؟

**Comment by javad-heidarpour** [comment]
min="1396/08/08"
  max="1396/09/09"

**Comment by mohammadoftadeh** [comment]
سلام
خواهش میکنم. در حال حاضر این ویژگی هایی که فرمودید در این پکیج ارائه نشده است و الان فقط انتخاب تاریخ بصورت ساده امکان پذیر هستش.
